In [1]:
import pandas as pd

# JSON TO PANDAS DATAFRAME

In [2]:
js = pd.read_json('train.json')

In [3]:
js

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

# SQL TO PANDAS DATAFRAME

In [9]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
     - ------------------------------------- 0.5/11.9 MB 932.9 kB/s eta 0:00:13
     --- ------------------------------------ 1.0/11.9 MB 1.5 MB/s eta 0:00:08
     ------ --------------------------------- 1.8/11.9 MB 2.2 MB/s eta 0:00:05
     ------ --------------------------------- 1.8/11.9 MB 2.2 MB/s eta 0:00:05
     --------------- ------------------------ 4.5/11.9 MB 3.6 MB/s eta 0:00:03
     ----------------- ---------------------- 5.2/11.9 MB 3.7 MB/s eta 0:00:02
     --------------------- ------------------ 6.3/11.9 MB 3.8 MB/s eta 0:00:02
     -------------------------- ------------- 7.9/11.9 MB 4.3 MB/s eta 0:00:01
     ----------------------------- ---------- 8.7/11.9 MB 4.2 MB/s eta 0:00:01
     ------------------------------ --------- 9.2/11.9 MB 4.1 MB/s eta 0:00:01
     -------------------------------- ------- 9.7/11.9 MB 4.0 MB/s eta 0:00:01
     ----------------------------------- ---- 10.5/11.9 MB 3.9 MB/s eta 0:00:01
     ------------------------------------- -- 11.0/11.9 MB 3.8 MB/s eta 0:00:01
     -------------------------------------- - 11.5/11.9 MB 3.7 MB/s eta 0:00:01
     -------------------------------------- - 11.5/11.9 MB 3.7 MB/s eta 0:00:01
     ---------------------------------------  11.8/11.9 MB 3.5 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 3.3 MB/s  0:00:04
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp311-cp311-win_amd64.whl size=248049 sha256=74787e8ff311a8687df242eea9143f84d837bc1826d5dd8e083e7eb23e2911b2
  Stored in directory: c:\users\prpth\appdata\local\pip\cache\wheels\17\cd\ed\2d49e9bac69cf09382e4c7cc20a2511202b48324b87db26019
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

In [4]:
import mysql.connector

In [6]:
tion = mysql.connector.connect(host='localhost',user='root',password='',database='world')

In [8]:
pd.read_sql_query("SELECT * FROM CITY WHERE CountryCode LIKE 'NEP'",tion)

C:\Users\prpth\AppData\Local\Temp\ipykernel_1204\176874055.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM CITY WHERE CountryCode LIKE 'NEP'",tion)

Empty DataFrame
Columns: [ID, Name, CountryCode, District, Population]
Index: []

In [10]:
pd.read_sql_query("SELECT * FROM CITY",tion)

C:\Users\prpth\AppData\Local\Temp\ipykernel_1204\666694532.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM CITY",tion)

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]