In [ ]:
import pandas as pd

In [2]:
df = pd.read_csv('House Price Prediction Dataset.csv')

In [3]:
df.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Id         2000 non-null   int64
 1   Area       2000 non-null   int64
 2   Bedrooms   2000 non-null   int64
 3   Bathrooms  2000 non-null   int64
 4   Floors     2000 non-null   int64
 5   YearBuilt  2000 non-null   int64
 6   Location   2000 non-null   str
 7   Condition  2000 non-null   str
 8   Garage     2000 non-null   str
 9   Price      2000 non-null   int64
dtypes: int64(7), str(3)
memory usage: 156.4 KB

In [33]:
df['Location'].value_counts()

Location
Downtown    558
Urban       485
Suburban    483
Rural       474
Name: count, dtype: int64

In [35]:
df['Condition'].value_counts()

Condition
Fair         521
Excellent    511
Poor         507
Good         461
Name: count, dtype: int64

In [36]:
df['Garage'].value_counts()

Garage
No     1038
Yes     962
Name: count, dtype: int64

In [7]:
df.sample()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
1546,1547,769,4,1,2,1993,Downtown,Poor,Yes,587488

In [9]:
X = df.drop('Price', axis=1)
y = df['Price']

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [14]:
X_train.sample(5)

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage
1486,1487,1456,5,4,3,1999,Downtown,Fair,No
1828,1829,2266,2,2,3,2015,Rural,Excellent,Yes
1637,1638,2167,2,3,1,1905,Urban,Good,No
925,926,1489,2,4,1,1928,Rural,Poor,Yes
766,767,3990,5,2,2,1953,Downtown,Good,Yes

In [15]:
import plotly.express as px

In [28]:
fig = px.scatter_3d(df, x='Area', y='Floors', z='Price',  size='Bathrooms', title='House Price vs Area')
fig.show()

In [23]:
import matplotlib.pyplot as plt

In [27]:
fig  =  plt.figure(figsize=(10, 6))
fig = px.scatter(df, x='Area', y='Price', title='House Price vs Area')
fig.show()

In [30]:
from sklearn.linear_model import LinearRegression

In [31]:
lr = LinearRegression()

In [38]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder


transformer = ColumnTransformer(transformers=[
    ('t1', OrdinalEncoder(categories=[['Rural', 'Suburban', 'Urban' ,'Downtown']]), ['Location']),
    ('t2', OrdinalEncoder(categories=[['Poor', 'Fair', 'Good', 'Excellent']]), ['Condition']),
    ('t3', OrdinalEncoder(categories=[['No', 'Yes']]), ['Garage']),
    ], remainder='passthrough')

In [ ]:
X_train_transformed = transformer.fit_transform(X_train)
X_test_transformed = transformer.transform(X_test)
X_train_transformed.shape

(1600, 9)

In [46]:
X_test_transformed.shape

(400, 9)

In [47]:
lr.fit(X_train_transformed, y_train)

LinearRegression()

In [48]:
y_pred = lr.predict(X_test_transformed)

In [49]:
from sklearn.metrics import mean_absolute_error, mean_squared_error,root_mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R2: {r2}")

MAE: 244272.2466077616
MSE: 78803223997.03828
RMSE: 280719.1194005821
R2: -0.012910161968338718