In [60]:
import numpy as np
import pandas as pd

In [61]:
df = pd.read_csv('titanic/train.csv')

In [62]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## Fill missing Age values with the median age grouped by Pclass and Sex

In [63]:
df.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [64]:
df['Age'].isnull().sum()

np.int64(177)

In [65]:
df.groupby(['Pclass','Sex'])['Age'].median()

Pclass  Sex
1       female    35.0
        male      40.0
2       female    28.0
        male      30.0
3       female    21.5
        male      25.0
Name: Age, dtype: float64

In [66]:
df['Age'] = df.groupby(['Pclass', 'Sex'])['Age'].transform(
    lambda x: x.fillna(x.median())
)

In [67]:
df.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,False,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

## Extract the Fare column as a NumPy array. Compute its mean, standard deviation, and the number of passengers who paid more than the mean fare.

In [68]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [69]:
fares = df['Fare'].values
fares

array([  7.25  ,  71.2833,   7.925 ,  53.1   ,   8.05  ,   8.4583,
        51.8625,  21.075 ,  11.1333,  30.0708,  16.7   ,  26.55  ,
         8.05  ,  31.275 ,   7.8542,  16.    ,  29.125 ,  13.    ,
        18.    ,   7.225 ,  26.    ,  13.    ,   8.0292,  35.5   ,
        21.075 ,  31.3875,   7.225 , 263.    ,   7.8792,   7.8958,
        27.7208, 146.5208,   7.75  ,  10.5   ,  82.1708,  52.    ,
         7.2292,   8.05  ,  18.    ,  11.2417,   9.475 ,  21.    ,
         7.8958,  41.5792,   7.8792,   8.05  ,  15.5   ,   7.75  ,
        21.6792,  17.8   ,  39.6875,   7.8   ,  76.7292,  26.    ,
        61.9792,  35.5   ,  10.5   ,   7.2292,  27.75  ,  46.9   ,
         7.2292,  80.    ,  83.475 ,  27.9   ,  27.7208,  15.2458,
        10.5   ,   8.1583,   7.925 ,   8.6625,  10.5   ,  46.9   ,
        73.5   ,  14.4542,  56.4958,   7.65  ,   7.8958,   8.05  ,
        29.    ,  12.475 ,   9.    ,   9.5   ,   7.7875,  47.1   ,
        10.5   ,  15.85  ,  34.375 ,   8.05  , 263.    ,   8.05  ,
         8.05  ,   7.8542,  61.175 ,  20.575 ,   7.25  ,   8.05  ,
        34.6542,  63.3583,  23.    ,  26.    ,   7.8958,   7.8958,
        77.2875,   8.6542,   7.925 ,   7.8958,   7.65  ,   7.775 ,
         7.8958,  24.15  ,  52.    ,  14.4542,   8.05  ,   9.825 ,
        14.4583,   7.925 ,   7.75  ,  21.    , 247.5208,  31.275 ,
        73.5   ,   8.05  ,  30.0708,  13.    ,  77.2875,  11.2417,
         7.75  ,   7.1417,  22.3583,   6.975 ,   7.8958,   7.05  ,
        14.5   ,  26.    ,  13.    ,  15.0458,  26.2833,  53.1   ,
         9.2167,  79.2   ,  15.2458,   7.75  ,  15.85  ,   6.75  ,
        11.5   ,  36.75  ,   7.7958,  34.375 ,  26.    ,  13.    ,
        12.525 ,  66.6   ,   8.05  ,  14.5   ,   7.3125,  61.3792,
         7.7333,   8.05  ,   8.6625,  69.55  ,  16.1   ,  15.75  ,
         7.775 ,   8.6625,  39.6875,  20.525 ,  55.    ,  27.9   ,
        25.925 ,  56.4958,  33.5   ,  29.125 ,  11.1333,   7.925 ,
        30.6958,   7.8542,  25.4667,  28.7125,  13.    ,   0.    ,
        69.55  ,  15.05  ,  31.3875,  39.    ,  22.025 ,  50.    ,
        15.5   ,  26.55  ,  15.5   ,   7.8958,  13.    ,  13.    ,
         7.8542,  26.    ,  27.7208, 146.5208,   7.75  ,   8.4042,
         7.75  ,  13.    ,   9.5   ,  69.55  ,   6.4958,   7.225 ,
         8.05  ,  10.4625,  15.85  ,  18.7875,   7.75  ,  31.    ,
         7.05  ,  21.    ,   7.25  ,  13.    ,   7.75  , 113.275 ,
         7.925 ,  27.    ,  76.2917,  10.5   ,   8.05  ,  13.    ,
         8.05  ,   7.8958,  90.    ,   9.35  ,  10.5   ,   7.25  ,
        13.    ,  25.4667,  83.475 ,   7.775 ,  13.5   ,  31.3875,
        10.5   ,   7.55  ,  26.    ,  26.25  ,  10.5   ,  12.275 ,
        14.4542,  15.5   ,  10.5   ,   7.125 ,   7.225 ,  90.    ,
         7.775 ,  14.5   ,  52.5542,  26.    ,   7.25  ,  10.4625,
        26.55  ,  16.1   ,  20.2125,  15.2458,  79.2   ,  86.5   ,
       512.3292,  26.    ,   7.75  ,  31.3875,  79.65  ,   0.    ,
         7.75  ,  10.5   ,  39.6875,   7.775 , 153.4625, 135.6333,
        31.    ,   0.    ,  19.5   ,  29.7   ,   7.75  ,  77.9583,
         7.75  ,   0.    ,  29.125 ,  20.25  ,   7.75  ,   7.8542,
         9.5   ,   8.05  ,  26.    ,   8.6625,   9.5   ,   7.8958,
        13.    ,   7.75  ,  78.85  ,  91.0792,  12.875 ,   8.85  ,
         7.8958,  27.7208,   7.2292, 151.55  ,  30.5   , 247.5208,
         7.75  ,  23.25  ,   0.    ,  12.35  ,   8.05  , 151.55  ,
       110.8833, 108.9   ,  24.    ,  56.9292,  83.1583, 262.375 ,
        26.    ,   7.8958,  26.25  ,   7.8542,  26.    ,  14.    ,
       164.8667, 134.5   ,   7.25  ,   7.8958,  12.35  ,  29.    ,
        69.55  , 135.6333,   6.2375,  13.    ,  20.525 ,  57.9792,
        23.25  ,  28.5   , 153.4625,  18.    , 133.65  ,   7.8958,
        66.6   , 134.5   ,   8.05  ,  35.5   ,  26.    , 263.    ,
        13.    ,  13.    ,  13.    ,  13.    ,  13.    ,  16.1   ,
        15.9   ,   8.6625,   9.225 ,  35.    ,   7.2292,  17.8   ,
         7.225 ,   9.5   ,  55.    ,  13.    ,   7.8792,   7.8792,
        27.9   ,  27.7208,  14.4542,   7.05  ,  15.5   ,   7.25  ,
        75.25  ,   7.2292,   7.75  ,  69.3   ,  55.4417,   6.4958,
         8.05  , 135.6333,  21.075 ,  82.1708,   7.25  , 211.5   ,
         4.0125,   7.775 , 227.525 ,  15.7417,   7.925 ,  52.    ,
         7.8958,  73.5   ,  46.9   ,  13.    ,   7.7292,  12.    ,
       120.    ,   7.7958,   7.925 , 113.275 ,  16.7   ,   7.7958,
         7.8542,  26.    ,  10.5   ,  12.65  ,   7.925 ,   8.05  ,
         9.825 ,  15.85  ,   8.6625,  21.    ,   7.75  ,  18.75  ,
         7.775 ,  25.4667,   7.8958,   6.8583,  90.    ,   0.    ,
         7.925 ,   8.05  ,  32.5   ,  13.    ,  13.    ,  24.15  ,
         7.8958,   7.7333,   7.875 ,  14.4   ,  20.2125,   7.25  ,
        26.    ,  26.    ,   7.75  ,   8.05  ,  26.55  ,  16.1   ,
        26.    ,   7.125 ,  55.9   , 120.    ,  34.375 ,  18.75  ,
       263.    ,  10.5   ,  26.25  ,   9.5   ,   7.775 ,  13.    ,
         8.1125,  81.8583,  19.5   ,  26.55  ,  19.2583,  30.5   ,
        27.75  ,  19.9667,  27.75  ,  89.1042,   8.05  ,   7.8958,
        26.55  ,  51.8625,  10.5   ,   7.75  ,  26.55  ,   8.05  ,
        38.5   ,  13.    ,   8.05  ,   7.05  ,   0.    ,  26.55  ,
         7.725 ,  19.2583,   7.25  ,   8.6625,  27.75  ,  13.7917,
         9.8375,  52.    ,  21.    ,   7.0458,   7.5208,  12.2875,
        46.9   ,   0.    ,   8.05  ,   9.5875,  91.0792,  25.4667,
        90.    ,  29.7   ,   8.05  ,  15.9   ,  19.9667,   7.25  ,
        30.5   ,  49.5042,   8.05  ,  14.4583,  78.2667,  15.1   ,
       151.55  ,   7.7958,   8.6625,   7.75  ,   7.6292,   9.5875,
        86.5   , 108.9   ,  26.    ,  26.55  ,  22.525 ,  56.4958,
         7.75  ,   8.05  ,  26.2875,  59.4   ,   7.4958,  34.0208,
        10.5   ,  24.15  ,  26.    ,   7.8958,  93.5   ,   7.8958,
         7.225 ,  57.9792,   7.2292,   7.75  ,  10.5   , 221.7792,
         7.925 ,  11.5   ,  26.    ,   7.2292,   7.2292,  22.3583,
         8.6625,  26.25  ,  26.55  , 106.425 ,  14.5   ,  49.5   ,
        71.    ,  31.275 ,  31.275 ,  26.    , 106.425 ,  26.    ,
        26.    ,  13.8625,  20.525 ,  36.75  , 110.8833,  26.    ,
         7.8292,   7.225 ,   7.775 ,  26.55  ,  39.6   , 227.525 ,
        79.65  ,  17.4   ,   7.75  ,   7.8958,  13.5   ,   8.05  ,
         8.05  ,  24.15  ,   7.8958,  21.075 ,   7.2292,   7.8542,
        10.5   ,  51.4792,  26.3875,   7.75  ,   8.05  ,  14.5   ,
        13.    ,  55.9   ,  14.4583,   7.925 ,  30.    , 110.8833,
        26.    ,  40.125 ,   8.7125,  79.65  ,  15.    ,  79.2   ,
         8.05  ,   8.05  ,   7.125 ,  78.2667,   7.25  ,   7.75  ,
        26.    ,  24.15  ,  33.    ,   0.    ,   7.225 ,  56.9292,
        27.    ,   7.8958,  42.4   ,   8.05  ,  26.55  ,  15.55  ,
         7.8958,  30.5   ,  41.5792, 153.4625,  31.275 ,   7.05  ,
        15.5   ,   7.75  ,   8.05  ,  65.    ,  14.4   ,  16.1   ,
        39.    ,  10.5   ,  14.4542,  52.5542,  15.7417,   7.8542,
        16.1   ,  32.3208,  12.35  ,  77.9583,   7.8958,   7.7333,
        30.    ,   7.0542,  30.5   ,   0.    ,  27.9   ,  13.    ,
         7.925 ,  26.25  ,  39.6875,  16.1   ,   7.8542,  69.3   ,
        27.9   ,  56.4958,  19.2583,  76.7292,   7.8958,  35.5   ,
         7.55  ,   7.55  ,   7.8958,  23.    ,   8.4333,   7.8292,
         6.75  ,  73.5   ,   7.8958,  15.5   ,  13.    , 113.275 ,
       133.65  ,   7.225 ,  25.5875,   7.4958,   7.925 ,  73.5   ,
        13.    ,   7.775 ,   8.05  ,  52.    ,  39.    ,  52.    ,
        10.5   ,  13.    ,   0.    ,   7.775 ,   8.05  ,   9.8417,
        46.9   , 512.3292,   8.1375,  76.7292,   9.225 ,  46.9   ,
        39.    ,  41.5792,  39.6875,  10.1708,   7.7958, 211.3375,
        57.    ,  13.4167,  56.4958,   7.225 ,  26.55  ,  13.5   ,
         8.05  ,   7.7333, 110.8833,   7.65  , 227.525 ,  26.2875,
        14.4542,   7.7417,   7.8542,  26.    ,  13.5   ,  26.2875,
       151.55  ,  15.2458,  49.5042,  26.55  ,  52.    ,   9.4833,
        13.    ,   7.65  , 227.525 ,  10.5   ,  15.5   ,   7.775 ,
        33.    ,   7.0542,  13.    ,  13.    ,  53.1   ,   8.6625,
        21.    ,   7.7375,  26.    ,   7.925 , 211.3375,  18.7875,
         0.    ,  13.    ,  13.    ,  16.1   ,  34.375 , 512.3292,
         7.8958,   7.8958,  30.    ,  78.85  , 262.375 ,  16.1   ,
         7.925 ,  71.    ,  20.25  ,  13.    ,  53.1   ,   7.75  ,
        23.    ,  12.475 ,   9.5   ,   7.8958,  65.    ,  14.5   ,
         7.7958,  11.5   ,   8.05  ,  86.5   ,  14.5   ,   7.125 ,
         7.2292, 120.    ,   7.775 ,  77.9583,  39.6   ,   7.75  ,
        24.15  ,   8.3625,   9.5   ,   7.8542,  10.5   ,   7.225 ,
        23.    ,   7.75  ,   7.75  ,  12.475 ,   7.7375, 211.3375,
         7.2292,  57.    ,  30.    ,  23.45  ,   7.05  ,   7.25  ,
         7.4958,  29.125 ,  20.575 ,  79.2   ,   7.75  ,  26.    ,
        69.55  ,  30.6958,   7.8958,  13.    ,  25.9292,   8.6833,
         7.2292,  24.15  ,  13.    ,  26.25  , 120.    ,   8.5167,
         6.975 ,   7.775 ,   0.    ,   7.775 ,  13.    ,  53.1   ,
         7.8875,  24.15  ,  10.5   ,  31.275 ,   8.05  ,   0.    ,
         7.925 ,  37.0042,   6.45  ,  27.9   ,  93.5   ,   8.6625,
         0.    ,  12.475 ,  39.6875,   6.95  ,  56.4958,  37.0042,
         7.75  ,  80.    ,  14.4542,  18.75  ,   7.2292,   7.8542,
         8.3   ,  83.1583,   8.6625,   8.05  ,  56.4958,  29.7   ,
         7.925 ,  10.5   ,  31.    ,   6.4375,   8.6625,   7.55  ,
        69.55  ,   7.8958,  33.    ,  89.1042,  31.275 ,   7.775 ,
        15.2458,  39.4   ,  26.    ,   9.35  , 164.8667,  26.55  ,
        19.2583,   7.2292,  14.1083,  11.5   ,  25.9292,  69.55  ,
        13.    ,  13.    ,  13.8583,  50.4958,   9.5   ,  11.1333,
         7.8958,  52.5542,   5.    ,   9.    ,  24.    ,   7.225 ,
         9.8458,   7.8958,   7.8958,  83.1583,  26.    ,   7.8958,
        10.5167,  10.5   ,   7.05  ,  29.125 ,  13.    ,  30.    ,
        23.45  ,  30.    ,   7.75  ])

In [70]:
means = np.mean(fares)
means

np.float64(32.204207968574636)

In [71]:
print(np.std(fares))

49.6655344447741

In [72]:
print(f"Fares who paid more the mean value is: {np.sum(means > fares)}")

Fares who paid more the mean value is: 680

## Using NumPy, create a new column FarePerPerson = Fare / (1 + SibSp + Parch). What is the maximum value?

In [75]:
fare = df['Fare'].values
sib = df['SibSp'].values
par = df['Parch'].values

In [76]:
df['FarePerPerson'] = fare/(1 + sib + par)

In [77]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FarePerPerson
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,3.62500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,35.64165
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7.92500
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,26.55000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,8.05000

## Use np.where() to create a new column AgeGroup: "Child" if Age < 18, else "Adult". How many children were on board?

In [78]:
age = df['Age'].values

In [79]:
age

array([22.  , 38.  , 26.  , 35.  , 35.  , 25.  , 54.  ,  2.  , 27.  ,
       14.  ,  4.  , 58.  , 20.  , 39.  , 14.  , 55.  ,  2.  , 30.  ,
       31.  , 21.5 , 35.  , 34.  , 15.  , 28.  ,  8.  , 38.  , 25.  ,
       19.  , 21.5 , 25.  , 40.  , 35.  , 21.5 , 66.  , 28.  , 42.  ,
       25.  , 21.  , 18.  , 14.  , 40.  , 27.  , 25.  ,  3.  , 19.  ,
       25.  , 25.  , 21.5 , 25.  , 18.  ,  7.  , 21.  , 49.  , 29.  ,
       65.  , 40.  , 21.  , 28.5 ,  5.  , 11.  , 22.  , 38.  , 45.  ,
        4.  , 40.  , 25.  , 29.  , 19.  , 17.  , 26.  , 32.  , 16.  ,
       21.  , 26.  , 32.  , 25.  , 25.  , 25.  ,  0.83, 30.  , 22.  ,
       29.  , 21.5 , 28.  , 17.  , 33.  , 16.  , 25.  , 23.  , 24.  ,
       29.  , 20.  , 46.  , 26.  , 59.  , 25.  , 71.  , 23.  , 34.  ,
       34.  , 28.  , 25.  , 21.  , 33.  , 37.  , 28.  , 21.  , 25.  ,
       38.  , 21.5 , 47.  , 14.5 , 22.  , 20.  , 17.  , 21.  , 70.5 ,
       29.  , 24.  ,  2.  , 21.  , 25.  , 32.5 , 32.5 , 54.  , 12.  ,
       25.  , 24.  , 21.5 , 45.  , 33.  , 20.  , 47.  , 29.  , 25.  ,
       23.  , 19.  , 37.  , 16.  , 24.  , 21.5 , 22.  , 24.  , 19.  ,
       18.  , 19.  , 27.  ,  9.  , 36.5 , 42.  , 51.  , 22.  , 55.5 ,
       40.5 , 25.  , 51.  , 16.  , 30.  , 25.  , 25.  , 44.  , 40.  ,
       26.  , 17.  ,  1.  ,  9.  , 35.  , 45.  , 40.  , 28.  , 61.  ,
        4.  ,  1.  , 21.  , 56.  , 18.  , 25.  , 50.  , 30.  , 36.  ,
       21.5 , 30.  ,  9.  ,  1.  ,  4.  , 40.  , 21.5 , 45.  , 40.  ,
       36.  , 32.  , 19.  , 19.  ,  3.  , 44.  , 58.  , 25.  , 42.  ,
       21.5 , 24.  , 28.  , 25.  , 34.  , 45.5 , 18.  ,  2.  , 32.  ,
       26.  , 16.  , 40.  , 24.  , 35.  , 22.  , 30.  , 25.  , 31.  ,
       27.  , 42.  , 32.  , 30.  , 16.  , 27.  , 51.  , 25.  , 38.  ,
       22.  , 19.  , 20.5 , 18.  , 21.5 , 35.  , 29.  , 59.  ,  5.  ,
       24.  , 21.5 , 44.  ,  8.  , 19.  , 33.  , 21.5 , 21.5 , 29.  ,
       22.  , 30.  , 44.  , 25.  , 24.  , 37.  , 54.  , 25.  , 29.  ,
       62.  , 30.  , 41.  , 29.  , 35.  , 30.  , 35.  , 50.  , 25.  ,
        3.  , 52.  , 40.  , 21.5 , 36.  , 16.  , 25.  , 58.  , 35.  ,
       40.  , 25.  , 41.  , 37.  , 21.5 , 63.  , 45.  , 30.  ,  7.  ,
       35.  , 65.  , 28.  , 16.  , 19.  , 40.  , 33.  , 30.  , 22.  ,
       42.  , 22.  , 26.  , 19.  , 36.  , 24.  , 24.  , 40.  , 23.5 ,
        2.  , 40.  , 50.  , 21.5 , 25.  , 19.  , 28.  , 25.  ,  0.92,
       35.  , 17.  , 30.  , 30.  , 24.  , 18.  , 26.  , 28.  , 43.  ,
       26.  , 24.  , 54.  , 31.  , 40.  , 22.  , 27.  , 30.  , 22.  ,
       25.  , 36.  , 61.  , 36.  , 31.  , 16.  , 21.5 , 45.5 , 38.  ,
       16.  , 35.  , 25.  , 29.  , 41.  , 45.  , 45.  ,  2.  , 24.  ,
       28.  , 25.  , 36.  , 24.  , 40.  , 21.5 ,  3.  , 42.  , 23.  ,
       40.  , 15.  , 25.  , 25.  , 28.  , 22.  , 38.  , 21.5 , 21.5 ,
       40.  , 29.  , 45.  , 35.  , 25.  , 30.  , 60.  , 21.5 , 21.5 ,
       24.  , 25.  , 18.  , 19.  , 22.  ,  3.  , 35.  , 22.  , 27.  ,
       20.  , 19.  , 42.  ,  1.  , 32.  , 35.  , 25.  , 18.  ,  1.  ,
       36.  , 25.  , 17.  , 36.  , 21.  , 28.  , 23.  , 24.  , 22.  ,
       31.  , 46.  , 23.  , 28.  , 39.  , 26.  , 21.  , 28.  , 20.  ,
       34.  , 51.  ,  3.  , 21.  , 21.5 , 25.  , 25.  , 33.  , 30.  ,
       44.  , 21.5 , 34.  , 18.  , 30.  , 10.  , 25.  , 21.  , 29.  ,
       28.  , 18.  , 25.  , 28.  , 19.  , 25.  , 32.  , 28.  , 21.5 ,
       42.  , 17.  , 50.  , 14.  , 21.  , 24.  , 64.  , 31.  , 45.  ,
       20.  , 25.  , 28.  , 25.  ,  4.  , 13.  , 34.  ,  5.  , 52.  ,
       36.  , 25.  , 30.  , 49.  , 25.  , 29.  , 65.  , 35.  , 50.  ,
       25.  , 48.  , 34.  , 47.  , 48.  , 25.  , 38.  , 30.  , 56.  ,
       25.  ,  0.75, 25.  , 38.  , 33.  , 23.  , 22.  , 40.  , 34.  ,
       29.  , 22.  ,  2.  ,  9.  , 30.  , 50.  , 63.  , 25.  , 21.5 ,
       35.  , 58.  , 30.  ,  9.  , 25.  , 21.  , 55.  , 71.  , 21.  ,
       25.  , 54.  , 25.  , 25.  , 24.  , 17.  , 21.  , 21.5 , 37.  ,
       16.  , 18.  , 33.  , 40.  , 28.  , 26.  , 29.  , 25.  , 36.  ,
       54.  , 24.  , 47.  , 34.  , 25.  , 36.  , 32.  , 30.  , 22.  ,
       25.  , 44.  , 25.  , 40.5 , 50.  , 40.  , 39.  , 23.  ,  2.  ,
       25.  , 17.  , 21.5 , 30.  ,  7.  , 45.  , 30.  , 25.  , 22.  ,
       36.  ,  9.  , 11.  , 32.  , 50.  , 64.  , 19.  , 30.  , 33.  ,
        8.  , 17.  , 27.  , 25.  , 22.  , 22.  , 62.  , 48.  , 40.  ,
       39.  , 36.  , 25.  , 40.  , 28.  , 25.  , 21.5 , 24.  , 19.  ,
       29.  , 25.  , 32.  , 62.  , 53.  , 36.  , 21.5 , 16.  , 19.  ,
       34.  , 39.  , 21.5 , 32.  , 25.  , 39.  , 54.  , 36.  , 25.  ,
       18.  , 47.  , 60.  , 22.  , 25.  , 35.  , 52.  , 47.  , 21.5 ,
       37.  , 36.  , 28.  , 49.  , 25.  , 49.  , 24.  , 25.  , 40.  ,
       44.  , 35.  , 36.  , 30.  , 27.  , 22.  , 40.  , 39.  , 25.  ,
       21.5 , 25.  , 35.  , 24.  , 34.  , 26.  ,  4.  , 26.  , 27.  ,
       42.  , 20.  , 21.  , 21.  , 61.  , 57.  , 21.  , 26.  , 25.  ,
       80.  , 51.  , 32.  , 40.  ,  9.  , 28.  , 32.  , 31.  , 41.  ,
       25.  , 20.  , 24.  ,  2.  , 25.  ,  0.75, 48.  , 19.  , 56.  ,
       25.  , 23.  , 25.  , 18.  , 21.  , 21.5 , 18.  , 24.  , 25.  ,
       32.  , 23.  , 58.  , 50.  , 40.  , 47.  , 36.  , 20.  , 32.  ,
       25.  , 25.  , 43.  , 35.  , 40.  , 31.  , 70.  , 31.  , 30.  ,
       18.  , 24.5 , 18.  , 43.  , 36.  , 21.5 , 27.  , 20.  , 14.  ,
       60.  , 25.  , 14.  , 19.  , 18.  , 15.  , 31.  ,  4.  , 25.  ,
       25.  , 60.  , 52.  , 44.  , 21.5 , 49.  , 42.  , 18.  , 35.  ,
       18.  , 25.  , 26.  , 39.  , 45.  , 42.  , 22.  , 25.  , 24.  ,
       40.  , 48.  , 29.  , 52.  , 19.  , 38.  , 27.  , 25.  , 33.  ,
        6.  , 17.  , 34.  , 50.  , 27.  , 20.  , 30.  , 21.5 , 25.  ,
       25.  , 29.  , 11.  , 30.  , 23.  , 23.  , 28.5 , 48.  , 35.  ,
       25.  , 25.  , 40.  , 36.  , 21.  , 24.  , 31.  , 70.  , 16.  ,
       30.  , 19.  , 31.  ,  4.  ,  6.  , 33.  , 23.  , 48.  ,  0.67,
       28.  , 18.  , 34.  , 33.  , 25.  , 41.  , 20.  , 36.  , 16.  ,
       51.  , 40.  , 30.5 , 25.  , 32.  , 24.  , 48.  , 57.  , 25.  ,
       54.  , 18.  , 25.  ,  5.  , 25.  , 43.  , 13.  , 17.  , 29.  ,
       25.  , 25.  , 25.  , 18.  ,  8.  ,  1.  , 46.  , 25.  , 16.  ,
       21.5 , 40.  , 25.  , 39.  , 49.  , 31.  , 30.  , 30.  , 34.  ,
       31.  , 11.  ,  0.42, 27.  , 31.  , 39.  , 18.  , 39.  , 33.  ,
       26.  , 39.  , 35.  ,  6.  , 30.5 , 40.  , 23.  , 31.  , 43.  ,
       10.  , 52.  , 27.  , 38.  , 27.  ,  2.  , 25.  , 25.  ,  1.  ,
       25.  , 62.  , 15.  ,  0.83, 25.  , 23.  , 18.  , 39.  , 21.  ,
       25.  , 32.  , 40.  , 20.  , 16.  , 30.  , 34.5 , 17.  , 42.  ,
       25.  , 35.  , 28.  , 35.  ,  4.  , 74.  ,  9.  , 16.  , 44.  ,
       18.  , 45.  , 51.  , 24.  , 25.  , 41.  , 21.  , 48.  , 21.5 ,
       24.  , 42.  , 27.  , 31.  , 25.  ,  4.  , 26.  , 47.  , 33.  ,
       47.  , 28.  , 15.  , 20.  , 19.  , 25.  , 56.  , 25.  , 33.  ,
       22.  , 28.  , 25.  , 39.  , 27.  , 19.  , 21.5 , 26.  , 32.  ])

In [83]:
df['AgeGroup'] = np.where(df['Age']<18,'child','adult')

In [84]:
df['AgeGroup'].value_counts()

AgeGroup
adult    778
child    113
Name: count, dtype: int64