In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('wine_data.csv',names=['class','Alcohol','Malic_acid','Ash','Alcalinity_of_ash','Magnesium','Total_phenols','Flavanoids','Nonflavanoid_phenols','Proanthocyanins','color_intensity','Hue','Diluted_wines','Proline'])
df.head()

,class,Alcohol,Malic_acid,Ash,Alcalinity_of_ash,Magnesium,Total_phenols,Flavanoids,Nonflavanoid_phenols,Proanthocyanins,color_intensity,Hue,Diluted_wines,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [4]:
df.sample(5)

,class,Alcohol,Malic_acid,Ash,Alcalinity_of_ash,Magnesium,Total_phenols,Flavanoids,Nonflavanoid_phenols,Proanthocyanins,color_intensity,Hue,Diluted_wines,Proline
157,3,12.45,3.03,2.64,27.0,97,1.90,0.58,0.63,1.14,7.50,0.67,1.73,880
158,3,14.34,1.68,2.70,25.0,98,2.80,1.31,0.53,2.70,13.00,0.57,1.96,660
109,2,11.61,1.35,2.70,20.0,94,2.74,2.92,0.29,2.49,2.65,0.96,3.26,680
103,2,11.82,1.72,1.88,19.5,86,2.50,1.64,0.37,1.42,2.06,0.94,2.44,415
104,2,12.51,1.73,1.98,20.5,85,2.20,1.92,0.32,1.48,2.94,1.04,3.57,672

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   class                 178 non-null    int64
 1   Alcohol               178 non-null    float64
 2   Malic_acid            178 non-null    float64
 3   Ash                   178 non-null    float64
 4   Alcalinity_of_ash     178 non-null    float64
 5   Magnesium             178 non-null    int64
 6   Total_phenols         178 non-null    float64
 7   Flavanoids            178 non-null    float64
 8   Nonflavanoid_phenols  178 non-null    float64
 9   Proanthocyanins       178 non-null    float64
 10  color_intensity       178 non-null    float64
 11  Hue                   178 non-null    float64
 12  Diluted_wines         178 non-null    float64
 13  Proline               178 non-null    int64
dtypes: float64(11), int64(3)
memory usage: 19.6 KB

In [1]:
import seaborn as sns

In [8]:
from sklearn.model_selection import train_test_split

x = df.drop('class',axis=1)
y = df['class']

In [9]:

X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [10]:
X_train.shape

(142, 13)

In [11]:
df.shape

(178, 14)

In [13]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [14]:
from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsClassifier

In [15]:
for i in range(1, 11):
    pca = PCA(n_components=i)
    X_train_pca = pca.fit_transform(X_train_scaled)
    X_test_pca = pca.transform(X_test_scaled)

    knn = KNeighborsClassifier(n_neighbors=3)
    knn.fit(X_train_pca, y_train)
    accuracy = knn.score(X_test_pca, y_test)
    print(f'Accuracy with {i} principal components: {accuracy:.4f}')

Accuracy with 1 principal components: 0.7778
Accuracy with 2 principal components: 1.0000
Accuracy with 3 principal components: 1.0000
Accuracy with 4 principal components: 0.9444
Accuracy with 5 principal components: 0.9444
Accuracy with 6 principal components: 0.9722
Accuracy with 7 principal components: 0.9722
Accuracy with 8 principal components: 0.9722
Accuracy with 9 principal components: 0.9444
Accuracy with 10 principal components: 0.9444

In [16]:
pca = PCA(n_components=2)
X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)

In [30]:
X_train_pca_df = pd.DataFrame(X_train_pca, columns=['PC1', 'PC2'])
X_train_pca_df.sample(5)

          PC1       PC2
2    2.283538 -1.275033
90  -1.429045 -0.967107
7   -0.715050 -0.202558
134  1.314532  0.285536
56  -0.400899 -2.309432

In [22]:
import plotly.express as px

fig = px.scatter(x=X_train_pca[:, 0], 
                 y=X_train_pca[:, 1], 
                 color=y_train.astype(str), 
                 color_discrete_sequence=px.colors.qualitative.G10,
                 labels={'x': 'Principal Component 1', 'y': 'Principal Component 2', 'color': 'Class'},
                 title='PCA of Wine Dataset')
fig.show()

In [23]:
pca3 = PCA(n_components=3)
X_train_pca3 = pca3.fit_transform(X_train_scaled)
X_test_pca3 = pca3.transform(X_test_scaled)

In [29]:
X_train_pca3_df = pd.DataFrame(X_train_pca3, columns=['PC1', 'PC2', 'PC3'])
X_train_pca3_df.sample(5)

          PC1       PC2       PC3
87   2.059748  1.646905  0.097085
30   1.300449  0.000093 -1.381941
23   2.561568  0.033089 -0.220327
134  1.314532  0.285536  5.263001
79   3.665227  2.952912 -0.094191

In [25]:
fig = px.scatter_3d(x=X_train_pca3[:, 0],
                    y=X_train_pca3[:, 1],
                    z=X_train_pca3[:, 2],
                    color=y_train.astype(str),
                    color_discrete_sequence=px.colors.qualitative.G10,)
fig.show()