In [2]:
import pandas as pd
import requests

In [24]:
import requests

url = "https://movies-ratings2.p.rapidapi.com/ratings"

querystring = {"id":"tt0111161"}

headers = {
	"x-rapidapi-key": "9aefd579damsh63dbca456128011p1e4427jsn7b854c8e400e",
	"x-rapidapi-host": "movies-ratings2.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

{'tmdbId': 278, 'imdbId': 'tt0111161', 'lastUpdated': 1738173381282, 'ratings': {'imdb': {'score': 9.3, 'reviewsCount': 3000000, 'url': 'https://www.imdb.com/title/tt0111161/'}, 'metacritic': {'metascore': 82, 'userScore': 9.3, 'averageScore': 8.8, 'url': 'https://www.metacritic.com/movie/the-shawshank-redemption'}, 'rotten_tomatoes': {'tomatometer': 89, 'tomatometerReviewsCount': 146, 'audienceScore': 98, 'audienceScoreReviewsCount': 250000, 'averageScore': 9.4, 'url': 'https://www.rottentomatoes.com/m/shawshank_redemption'}, 'letterboxd': {'score': 4.6, 'url': 'https://letterboxd.com/film/the-shawshank-redemption'}, 'allocine': None, 'average': {'score': 9.12}}, 'media': {'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg', 'budget': 25000000, 'genres': [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name': 'Crime'}], 'homepage': '', 'id': 278, 'imdb_id': 'tt0111161', 'origin_country': ['US'], 'original_language': 'en', 'original_title': 'The Shawshank Redemption', 'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.', 'popularity': 173.309, 'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg', 'release_date': '1994-09-23', 'revenue': 28341469, 'runtime': 142, 'spoken_languages': [{'english_name': 'English', 'iso_639_1': 'en', 'name': 'English'}], 'status': 'Released', 'tagline': 'Fear can hold you prisoner. Hope can set you free.', 'title': 'The Shawshank Redemption', 'video': False, 'external_ids': {'imdb_id': 'tt0111161', 'wikidata_id': 'Q172241', 'facebook_id': None, 'instagram_id': None, 'twitter_id': None}, 'director': 'Frank Darabont', 'media_type': 'movie'}}

In [25]:
pd.DataFrame(response.json()['ratings'])

,imdb,metacritic,rotten_tomatoes,letterboxd,allocine,average
score,9.3,NaN,NaN,4.6,None,9.12
reviewsCount,3000000,NaN,NaN,NaN,None,NaN
url,https://www.imdb.com/title/tt0111161/,https://www.metacritic.com/movie/the-shawshank...,https://www.rottentomatoes.com/m/shawshank_red...,https://letterboxd.com/film/the-shawshank-rede...,None,NaN
metascore,NaN,82,NaN,NaN,None,NaN
userScore,NaN,9.3,NaN,NaN,None,NaN
averageScore,NaN,8.8,9.4,NaN,None,NaN
tomatometer,NaN,NaN,89,NaN,None,NaN
tomatometerReviewsCount,NaN,NaN,146,NaN,None,NaN
audienceScore,NaN,NaN,98,NaN,None,NaN
audienceScoreReviewsCount,NaN,NaN,250000,NaN,None,NaN

In [35]:
df = pd.DataFrame(response.json()['ratings'])[['imdb','average','metacritic']]

In [36]:
df

,imdb,average,metacritic
score,9.3,9.12,NaN
reviewsCount,3000000,NaN,NaN
url,https://www.imdb.com/title/tt0111161/,NaN,https://www.metacritic.com/movie/the-shawshank...
metascore,NaN,NaN,82
userScore,NaN,NaN,9.3
averageScore,NaN,NaN,8.8
tomatometer,NaN,NaN,NaN
tomatometerReviewsCount,NaN,NaN,NaN
audienceScore,NaN,NaN,NaN
audienceScoreReviewsCount,NaN,NaN,NaN

In [37]:
df.to_csv('ratingss.csv')