In [16]:
import numpy as np
import pandas as pd

In [17]:
np.random.seed(42)

In [18]:
mu_vec1 = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])

In [19]:
class_samples = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)

In [20]:
class_samples

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439],
       [ 0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783],
       [-0.56228753, -1.01283112,  0.31424733],
       [-0.90802408, -1.4123037 ,  1.46564877],
       [-0.2257763 ,  0.0675282 , -1.42474819],
       [-0.54438272,  0.11092259, -1.15099358],
       [ 0.37569802, -0.60063869, -0.29169375],
       [-0.60170661,  1.85227818, -0.01349722],
       [-1.05771093,  0.82254491, -1.22084365],
       [ 0.2088636 , -1.95967012, -1.32818605],
       [ 0.19686124,  0.73846658,  0.17136828],
       [-0.11564828, -0.3011037 , -1.47852199],
       [-0.71984421, -0.46063877,  1.05712223],
       [ 0.34361829, -1.76304016,  0.32408397],
       [-0.38508228, -0.676922  ,  0.61167629],
       [ 1.03099952,  0.93128012, -0.83921752],
       [-0.30921238,  0.33126343,  0.97554513]])

In [21]:
df = pd.DataFrame(class_samples, columns=['X1', 'X2', 'X3'])
df['target'] = 1
df

          X1        X2        X3  target
0   0.496714 -0.138264  0.647689       1
1   1.523030 -0.234153 -0.234137       1
2   1.579213  0.767435 -0.469474       1
3   0.542560 -0.463418 -0.465730       1
4   0.241962 -1.913280 -1.724918       1
5  -0.562288 -1.012831  0.314247       1
6  -0.908024 -1.412304  1.465649       1
7  -0.225776  0.067528 -1.424748       1
8  -0.544383  0.110923 -1.150994       1
9   0.375698 -0.600639 -0.291694       1
10 -0.601707  1.852278 -0.013497       1
11 -1.057711  0.822545 -1.220844       1
12  0.208864 -1.959670 -1.328186       1
13  0.196861  0.738467  0.171368       1
14 -0.115648 -0.301104 -1.478522       1
15 -0.719844 -0.460639  1.057122       1
16  0.343618 -1.763040  0.324084       1
17 -0.385082 -0.676922  0.611676       1
18  1.031000  0.931280 -0.839218       1
19 -0.309212  0.331263  0.975545       1

In [22]:
mu_vec2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_samples = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)

In [23]:
class2_samples
df2 = pd.DataFrame(class2_samples, columns=['X1', 'X2', 'X3'])
df2['target'] = 0

In [24]:
df = pd.concat([df, df2], ignore_index=True)

In [25]:
df.sample(4)

          X1        X2        X3  target
32  1.296120  1.261055  1.005113       0
36  1.257550  0.925554 -0.918771       0
35  1.404051  2.886186  1.174578       0
22  0.927990  2.003533  1.361636       0

In [26]:
import plotly.express as px

In [27]:
fig = px.scatter_3d(df, x='X1', y='X2', z='X3', color='target')
fig.update_traces(marker=dict(size=5, line=dict(width=2, color='DarkSlateGrey')), selector=dict(mode='markers'))
fig.show()