In [15]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer,KNNImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [16]:
df = pd.read_csv('titanic/train.csv',usecols=['Age','Pclass','Fare','Survived'])

In [17]:
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [18]:
df.isnull().mean() * 100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [19]:
X = df.drop('Survived',axis=1)
y = df['Survived']

In [20]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [21]:
X_train

     Pclass   Age      Fare
331       1  45.5   28.5000
733       2  23.0   13.0000
382       3  32.0    7.9250
704       3  26.0    7.8542
813       3   6.0   31.2750
..      ...   ...       ...
106       3  21.0    7.6500
270       1   NaN   31.0000
860       3  41.0   14.1083
435       1  14.0  120.0000
102       1  21.0   77.2875

[712 rows x 3 columns]

In [25]:
knn = KNNImputer(weights='distance')
X_train_knn = knn.fit_transform(X_train)
X_test_knn = knn.transform(X_test)

In [26]:
pd.DataFrame(X_train_knn,columns=X_train.columns)

     Pclass        Age      Fare
0       1.0  45.500000   28.5000
1       2.0  23.000000   13.0000
2       3.0  32.000000    7.9250
3       3.0  26.000000    7.8542
4       3.0   6.000000   31.2750
..      ...        ...       ...
707     3.0  21.000000    7.6500
708     1.0  40.111111   31.0000
709     3.0  41.000000   14.1083
710     1.0  14.000000  120.0000
711     1.0  21.000000   77.2875

[712 rows x 3 columns]

In [27]:
lr = LogisticRegression()
lr.fit(X_train_knn,y_train)
y_pred = lr.predict(X_test_knn)
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.7374301675977654